In [1]:
import pandas as pd
from scipy.stats import mannwhitneyu

In [13]:
df = pd.read_excel('Данные для тестового задания.xlsx', sheet_name=1)
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [14]:
experiment = df['experiment_num'].unique()
experiment

array([1, 2, 3])

In [15]:
for i in experiment:
    data = df[df['experiment_num'] == i]

    control_group_rev = data[data['experiment_group'] == 'control']['revenue']
    test_group_rev = data[data['experiment_group'] == 'test']['revenue']

    stat, p_value = mannwhitneyu(control_group_rev, test_group_rev, alternative='two-sided')

    arpu_control_group = control_group_rev.mean()
    arpu_test_group = test_group_rev.mean()

    print(f'AB test for experiment_num: {i}')
    print(f'ARPU control: {arpu_control_group:.2f}')
    print(f'ARPU test: {arpu_test_group:.2f}')
    print(f'p-value: {p_value:.4f}')
    print('='*50)

AB test for experiment_num: 1
ARPU control: 722.46
ARPU test: 665.74
p-value: 0.7960
==================================================
AB test for experiment_num: 2
ARPU control: 704.65
ARPU test: 332.93
p-value: 0.0085
==================================================
AB test for experiment_num: 3
ARPU control: 663.21
ARPU test: 998.67
p-value: 0.0010
==================================================

In [16]:
df2 = pd.read_excel('Данные для тестового задания.xlsx', sheet_name=2)
df2.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       158 non-null    int64
 1   date          158 non-null    datetime64[ns]
 2   cnt_adverts   158 non-null    int64
 3   age           158 non-null    int64
 4   cnt_contacts  158 non-null    int64
 5   revenue       158 non-null    int64
dtypes: datetime64[ns](1), int64(5)
memory usage: 7.5 KB

In [26]:
users_grouped = df2.groupby('user_id').agg({'revenue': 'sum', 'age': 'first'})
users_grouped.head()

         revenue  age
user_id
100          261   21
101          115   30
102           93   34
103          138   36
104          168   21

In [27]:
ARPU = users_grouped['revenue'].mean()
ARPU

np.float64(156.48387096774192)

In [29]:
age_median = users_grouped['age'].median()
age_median

28.0

In [34]:
(1099 / 100001055) - (1003 / 100047501)

9.646461449836582e-07